# --- Identidad del repositorio ---
owner: arosa-cor
repo: coregistros

# --- Intervalo entre checks (ms) ---
delay: 2000   # 2 segundos entre peticiones para evitar ráfagas

# --- Sitios a monitorizar ---
sites:
  - name: coregistros.com
    url: https://www.coregistros.com
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: blog.sorteopremios.com (API WP)
    url: https://blog.sorteopremios.com/wp-json/
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"
      - "Accept: application/json,*/*;q=0.8"
      - "Accept-Language: es-ES,es;q=0.9,en;q=0.8"
      - "Cache-Control: no-cache"

  - name: mitest.de
    url: https://mitest.de
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: bevrand.com
    url: https://www.bevrand.com
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: milopciones.es
    url: https://milopciones.es
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []           # añade aquí usuarios de GitHub si quieres notificaciones
    type: globalping        # opcional, requiere GLOBALPING_TOKEN
    location: europe

  - name: g0crm.info (API WP)
    url: https://g0crm.info/wp-json/
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe
    headers:
      - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36"
      - "Accept: application/json,*/*;q=0.8"
      - "Accept-Language: es-ES,es;q=0.9,en;q=0.8"

# --- Gobernanza de incidentes ---
assignees: []             # asignados por defecto si no hay por-site
skipDeleteIssues: true    # conserva incidencias cortas (<15 min)

# --- Status website ---
status-website:
  name: Estado de Servicios – Coregistros
  theme: dark
  baseUrl: /coregistros
  logoUrl: https://www.coregistros.com/wp-content/uploads/2022/07/cropped-coregistros-favicon-32x32.png
