# --- Identidad del repositorio ---
owner: arosa-cor
repo: coregistros

# --- Intervalo entre checks (ms) ---
delay: 2000   # 2 segundos entre peticiones para evitar ráfagas

# --- Sitios a monitorizar ---
sites:
  - name: milopciones.es
    url: https://milopciones.es
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []           # añade aquí usuarios de GitHub si quieres notificaciones

    type: globalping        # opcional, requiere GLOBALPING_TOKEN
    location: europe

  - name: coregistros.com
    url: https://www.coregistros.com
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: blog.sorteopremios.com
    url: https://blog.sorteopremios.com
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: 

  - name: g0crm.info
    url: https://g0crm.info
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

  - name: mitest.de
    url: https://mitest.de
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe
# --- Gobernanza de incidentes ---
assignees: []             # asignados por defecto si no hay por-site
skipDeleteIssues: true    # conserva incidencias cortas (<15 min)

# --- Status website ---
status-website:
  name: Estado de Servicios – Coregistros
  theme: dark
  baseUrl: /coregistros
  logoUrl: https://www.coregistros.com/wp-content/uploads/2022/07/cropped-coregistros-favicon-32x32.png
