# --- Identidad del repositorio ---
owner: arosa-cor
repo: coregistros

# --- Intervalo entre checks (ms) ---
delay: 2000   # 2 segundos entre peticiones para evitar ráfagas

# --- Sitios a monitorizar ---
sites:
  - name: Milopciones (WWW)
    url: https://www.milopciones.es
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []           # añade aquí usuarios de GitHub si quieres notificaciones

    type: globalping        # opcional, requiere GLOBALPING_TOKEN
    location: europe

  - name: CoRegistros (WWW)
    url: https://www.coregistros.com
    expectedStatusCodes:
      - 200
      - 201-299
      - 301-308
    maxResponseTime: 4000
    assignees: []
    type: globalping
    location: europe

# --- Gobernanza de incidentes ---
assignees: []             # asignados por defecto si no hay por-site
skipDeleteIssues: true    # conserva incidencias cortas (<15 min)

# --- Status website ---
status-website:
  name: Estado de Servicios – Coregistros
  theme: dark
  baseUrl: /coregistros
  logoUrl: https://www.coregistros.com/wp-content/uploads/2022/07/cropped-coregistros-favicon-32x32.png
